spring:
  profiles:
    active: ${PROFILE:dev}
  application:
    name: verimly
  config:
    import:
      - classpath:verimly-prod.yml
      - classpath:verimly-dev.yml

security:
  sign-up-path: /api/v1/users
  login-path: /api/v1/auth/login
  logout-path: /api/v1/auth/logout
  username-parameter: email
  password-parameter: password
  cors:
    path: /**
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
      - PATCH
    allowed-headers:
      - Authorization
      - Cache-Control
      - Content-Type
      - X-Requested-With
      - X-Csrf-Token
      - X-TimeZone
    allow-credentials: true
    max-age: 3600
  jwt:
    issuer: verimly
    email-claim: email
  access-token-cookie:
    name: access_token
    http-only: true
    path: /
# All environment-specific settings are now in verimly-dev.yml and verimly-prod.yml
# This file only activates profiles, imports config, and holds common properties.
