spring:
  config:
    activate:
      on-profile: dev
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  h2:
    console:
      enabled: true
#  output:
#    ansi:
#      enabled: ALWAYS



security:
  sign-up-path: "/api/v1/users"
  login-path: "/api/v1/auth/login"
  username-parameter: "email"
  password-parameter: "password"
  front-end-origin: http://localhost:5173
  cors:
    path: /**
    allowed-origins:
      - "http://localhost:5173"
      - "http://localhost:3000"
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
      - PATCH
    allowed-headers:
      - Authorization
      - Cache-Control
      - Content-Type
      - X-Requested-With
      - X-Csrf-Token
      - X-TimeZone
    allow-credentials: true
    max-age: 3600
  jwt:
    expires-in: 86400000
    secret-key: mydevsecretkeymydevsecretkeymydevsecretkey
    issuer: verimly
    email-claim: email
  access-token-cookie:
    name: access_token
    http-only: true
    secure: false
    same-site: Lax
    max-age-seconds: 86400
    path: /
    domain: localhost


logging:
  pattern:
    console: "%red(%date)  %highlight(%-5level) [%12.12thread] %red(%-40.40logger{40}) : %green(%msg) %n"
    #    console: "%d{yyyy-MM-dd HH:mm:ss} %highlight(%-5level) [%thread] %cyan(%logger{36}) - %msg%n"
  level:
    app.verimly: TRACE
    org.springframework.security: TRACE