spring:
  config:
    activate:
      on-profile: prod
  sql:
    init:
      mode: ${SPRING_SQL_INIT_MODE:never}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    open-in-view: false
    defer-datasource-initialization: false
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  h2:
    console:
      enabled: false

security:
  front-end-origin: ${FE_ORIGIN}
  cors:
    allowed-origins:
      - ${FE_ORIGIN}
    max-age: ${CORS_MAX_AGE}
  jwt:
    expires-in: ${JWT_EXPIRES_IN}
    secret-key: ${JWT_SECRET_KEY}
  access-token-cookie:
    secure: true
    same-site: ${COOKIE_SAME_SITE:None}
    max-age-seconds: ${COOKIE_MAX_AGE:3600}
    domain: ${COOKIE_DOMAIN:""}

bootstrap:
  user:
    firstName: ${BOOTSTRAP_USER_FIRSTNAME}
    lastName: ${BOOTSTRAP_USER_LASTNAME}
    email: ${BOOTSTRAP_USER_EMAIL}
    password: ${BOOTSTRAP_USER_PASSWORD}

logging:
  pattern:
    console: "%red(%date)  %highlight(%-5level) [%12.12thread] %red(%-40.40logger{40}) : %green(%msg) %n"
    #    console: "%d{yyyy-MM-dd HH:mm:ss} %highlight(%-5level) [%thread] %cyan(%logger{36}) - %msg%n"
  level:
    app.verimly: ${LOG_LEVEL:INFO}
server:
  port: ${PORT:8080}
