spring:
  config:
    activate:
      on-profile: dev
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
    defer-datasource-initialization: false
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  h2:
    console:
      enabled: true
#  output:
#    ansi:
#      enabled: ALWAYS



security:
  front-end-origin: http://localhost:3000
  cors:
    allowed-origins:
      - ${security.front-end-origin}
  jwt:
    expires-in: 86400000
    secret-key: mydevsecretkeymydevsecretkeymydevsecretkey
  access-token-cookie:
    secure: false
    same-site: Lax
    max-age-seconds: 86400
    domain: localhost

bootstrap:
  user:
    firstName: Muhammet
    lastName: Şener
    email: muhsener@verimly.com
    password: muhsener


logging:
  pattern:
    console: "%red(%date)  %highlight(%-5level) [%12.12thread] %red(%-40.40logger{40}) : %green(%msg) %n"
    #    console: "%d{yyyy-MM-dd HH:mm:ss} %highlight(%-5level) [%thread] %cyan(%logger{36}) - %msg%n"
  level:
    app.verimly: TRACE
    org.springframework.security: TRACE