spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  h2:
    console:
      enabled: true



security:
  sign-up-path: "/api/v1/users"
  login-path: "/api/v1/auth/login"
  username-parameter: "email"
  password-parameter: "password"
  front-end-origin: http://localhost:5173
  cors:
    path: /**
    allowed-origins:
      - "http://localhost:5173"
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
      - PATCH
    allowed-headers:
      - Authorization
      - Cache-Control
      - Content-Type
      - X-Requested-With
      - X-Csrf-Token
    allow-credentials: true
    max-age: 3600
  jwt:
    expires-in: 1000
    secret-key: mydevsecretkeymydevsecretkeymydevsecretkey
    issuer: verimly
    email-claim: email
  access-token-cookie:
    name: access_token
    http-only: true
    secure: false
    same-site: Lax
    max-age-seconds: 86400
    path: /
    domain: localhost


logging:
  level:
    app.verimly: TRACE
    org.springframework.security: TRACE