spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  h2:
    console:
      enabled: true



security:
  sign-up-path: "/api/v1/users"
  front-end-origin: http://localhost:5173
  cors:
    path: /**
    allowed-origins:
      - "http://localhost:5173"
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
      - PATCH
    allowed-headers:
      - Authorization
      - Cache-Control
      - Content-Type
      - X-Requested-With
      - X-Csrf-Token
    allow-credentials: true
    max-age: 3600

logging:
  level:
    app.verimly: TRACE
    org.springframework.security: TRACE